# Generated by Django 3.1.4 on 2021-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=200)),
                ('possition_of_user', models.CharField(max_length=200)),
                ('age_of_user', models.IntegerField(max_length=500)),
            ],
        ),
    ]
